system_name: kinematic_car
title: Kinematic Car
start_state: [-0.2, 0.0, 0.0]
goal_state: [3.0, 3.0, 1.5708]
state_bounds:
  - [-6.0, 6.0]
  - [-6.0, 6.0]
control_bounds:
  - [-0.2, 0.95]
  - [-0.30, 0.30]
goal_threshold: 0.2
propagation_step_size: 1.0
min_control_duration: 1
max_control_duration: 5
obstacles: {enabled: false}

environments:
  gaussian:
    panel_id: kinematic_car_gaussian
    panel_subtitle: Gaussian Noise
    simulator_mode: gaussian
    sampling_position_std: 0.0025
    sampling_rotation_std: 0.025
    sampling_velocity_std: 0.0025
    state_bounds:
      - [-10.0, 10.0]
      - [-10.0, 10.0]
  mujoco:
    panel_id: kinematic_car_mujoco
    panel_subtitle: MuJoCo Simulation
    simulator_mode: mujoco
    sampling_position_std: 0.0
    sampling_rotation_std: 0.0
    sampling_velocity_std: 0.0
    state_bounds:
      - [-10.0, 10.0]
      - [-10.0, 10.0]
    mujoco_car_throttle_ctrl_scale: 0.08
    mujoco_car_steering_ctrl_scale: 1.1
    headless: true
